version: '3.7'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:13
    networks:
      - webnet
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: testdb
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgresdb
    networks:
      - webnet
    ports:
      - 8081:8080
networks:
  webnet:
volumes:
  pgdata:
