version: '3.7'

services:
  postgresdb:
    image: postgres:13
    container_name: postgresdb
    networks:
      - webnet
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: testdb
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgresdb
    networks:
      - webnet
    ports:
      - 8081:8080

#  frontend:
#    depends_on:
#      - backend
#    build:
#      context: frontend
#      dockerfile: Dockerfile.dev
#    command: ng serve --host 0.0.0.0 --poll 1 --port 4200
#    restart: always
#    ports:
#      - 4200:4200
#    volumes:
#      - ./frontend:/usr/src/app

  backend:
    networks:
      - webnet
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/testdb

networks:
  webnet:
volumes:
  pgdata:
